packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@better-auth/cli": 1.3.27
  "@better-auth/expo": 1.3.27
  "@eslint/js": ^9.38.0
  "@expo/metro-runtime": ^6.1.2
  "@tailwindcss/postcss": ^4.1.16
  "@tailwindcss/vite": ^4.1.16
  "@tanstack/react-form": ^1.23.8
  "@tanstack/react-query": 5.90.5
  "@trpc/client": ^11.7.0
  "@trpc/server": ^11.7.0
  "@trpc/tanstack-react-query": ^11.7.0
  "@types/node": ^22.18.12
  "@vitejs/plugin-react": 5.1.0
  better-auth: 1.3.27
  eslint: ^9.38.0
  prettier: ^3.6.2
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  vite: 7.1.12
  zod: ^4.1.12

catalogs:
  react19:
    "@types/react": ~19.1.10
    "@types/react-dom": ~19.1.7
    react: 19.1.0
    react-dom: 19.1.0

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 5.1.2
  vite: 7.1.12
  ws: ^6.1.2

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
